### ISSUE TITLE
Alpha Release Roadmap

### ISSUE THREAD

**Issue by linux-china** [alibaba/alibaba-rsocket-broker#37]
准备Alpha1的版本发布，一些要解决的核心问题：

- RSocket
  - [ ] RSocket Java SDK 1.0.0
- Development 
  - [x] Deploy artifacts to Maven central repository(进行中)
  - [x] External apps integration from outside of the cluster network
  - [x] Integration testing for all features
  - [x] JDK 8, 11 & 14 compatible  testing
- Deployment
  -  [x]  Dev deployment
  -  [x]  Gossip cluster deployment
- Documents
  - [x]  Alibaba RSocket Broker Website
  - [x] Alibaba RSocket Broker Wiki

如果大家还有一些比较关注的问题，这里可以留言一下。

**Comment by linux-china** [comment]
MileStone 1已经完成发布：  https://github.com/alibaba/alibaba-rsocket-broker/releases/tag/1.0.0.M1
